
spring:

  # servlet
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 0B
      max-file-size: 100MB
      max-request-size: 100MB

  # format
  jackson:
    property-naming-strategy: SNAKE_CASE

  # jdbc
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    url: ${DB_URL}

  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}

  # jpa
  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:update}
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false

# server
server:
  port: ${SERVER_PORT:8080}
  tomcat:
    connection-timeout: -1

# logging
logging:
  level:
    root: info

jwt:
  secret-key: ${JWT_SECRET}
  access-exp: ${ACCESS_EXP}
  refresh-exp: ${REFRESH_EXP}

cloud:
  aws:
    s3:
      bucket: ${BUCKET}
      dir: ${DIRECTORY}
      accessKey: ${IAM_ACCESS}
      secretKey: ${IAM_SECRET}
      region: ap-northeast-2